sudo: false
language: minimal
git:
  submodules: false # Do not clone submodules until later.
cache:
  directories:
  - $HOME/.stack

matrix:
  include:
  - env: STACK_YAML=stack-8.4.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.4.4
        - build-essential
  - env: STACK_YAML=stack-8.6.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.6.4
        - build-essential

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

# Changes ssh paths into http path, so that we can do a read-only clone of
# our submodules without worrying about ssh keys.
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init

# Download stack
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
 # Setup GHC using stack
 - travis_wait stack --stack-yaml stack.yaml setup
 - stack --no-terminal --system-ghc build flexdis86 --ghc-options="-Wall -Werror"
 - stack --no-terminal --system-ghc test  flexdis86 --ghc-options="-Wall -Werror"
